// <auto-generated />
namespace QuanLyBanHang.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class alter_table_NhanVien_SDT : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(alter_table_NhanVien_SDT));
        
        string IMigrationMetadata.Id
        {
            get { return "202105050125564_alter_table_NhanVien_SDT"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
